spring:
  application:
    name: sama-souf-api

  profiles:
    active: local

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        envers:
          audit_table_suffix: _AUD
          revision_field_name: REV
          revision_type_field_name: REVTYPE
          store_data_at_delete: true
          default_schema: public

server:
  port: 8080
  max-http-header-size: 16384
  max-request-size: 10485760 # 10 MB
  max-response-size: 10485760 # 10 MB
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /management

  logging:
    pattern:
      level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
