spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sama_souf_db
    username: postgres
    password: Nicola93
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
